"/query/{dataset-uuid}/sparql": {
    "get": {
        "tags": [
            "<?= $tag ?>"
        ],
        "summary": "Retrieve sparql",
        "operationId": "getSparql",
        "parameters": [
          {
              "name": "dataset-uuid",
            "in": "path",
            "description": "Dataset name",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
            {
                "name": "query",
                "in": "query",
                "description": "The SPARQL query",
                "required": true,
                "schema": {
                    "type": "string"
                }
            }
        ],
        "responses": {
"200": {
"description": "Query results",
"content": {
"application/sparql-results+json": {
"schema": {
"type": "object"
}
},
"application/sparql-results+xml": {
"schema": {
"type": "object"
}
},
"text/csv": {
"schema": {
"type": "string",
"example": "subject,predicate,object"
}
},
"text/tab-separated-values": {
"schema": {
"type": "string",
"example": "?subject	?predicate	?object"
}
},
"application/x-binary-rdf-results-table": {
"schema": {
"format": "binary"
}
}
}
},
          "400": {
                "description": "Bad request or malformed SPARQL"
          },
          "500": {
                "description": "Fatal error"
          }
        }
      }
    },
